# Site settings
title: Connectal Project
email: jamey.hicks@qrclab.com
description: > # this means to ignore newlines until "baseurl:"
  Connectal supports flexible and consistent partitioning of
  accelerated applications across hardware and software
  components. The Connectal framework connects hardware and software
  via remote asynchronous method invocation by compiling interface
  declarations. It enables concurrent access to hardware accelerators
  from software. Connectal enables high-bandwidth sharing of system
  memory with hardware accelerators. Connectal provides portability
  across platforms.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.connectal.org" # the base hostname & protocol for your site
archive: /archive
feed: /atom.xml
gems:
  - jekyll-sitemap
googleplus_id: 117959521328494879184
googleplus_username: Connectal
twitter_username: connectalproj
github_username:  cambridgehackers
tag_page_layout: tag_page
tag_page_dir: tag
# Build settings
markdown: kramdown
